name:  CI/CD   # deploy wiht azure or github pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

  workflow_dispatch:
    inputs: 
      deploy_target:
        description: 'Deployment target'
        required: true
        default: 'github-pages'  # use 'azure' for deploy on azure static web app

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    environment:
      name: production
    
    env:
      APP_SERVICE_ID: ${{secrets.APP_SERVICE_ID}} # mail app service id
      APP_TEMPLATE_ID: ${{secrets.APP_TEMPLATE_ID}} # mail app template id
      APP_PUBLIC_KEY: ${{secrets.APP_PUBLIC_KEY}} # mail app key

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
        
      - name: Build And Deploy to Azure
        id: builddeploy
        if: ${{ github.event.inputs.deploy_target == 'azure'}}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_PEBBLE_0FEFC0910 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      - name: Build and deploy to Github Pages
        if: ${{ github.event.inputs.deploy_target == 'github-pages'}}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request on Azure
        if: ${{ github.event.inputs.deploy_target == 'azure'}}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_PEBBLE_0FEFC0910 }}
          action: "close"

      - name: Close Pull Request on GitHub Pages
        if: ${{ github.event.inputs.deploy_target == 'github-pages'}}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Closing pull request for GitHub Pages deployment"
